# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request: 
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306
        options:
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
      redis:
        image: redis
        ports: 
          ['6379:6379']
        options:
          --entrypoint redis-server
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v1            
    - name: Init Database      
    - run: |        
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE USER root@localhost IDENTIFIED BY "root"'        
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE test'        
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE testcode'        
        mysql -uroot -h127.0.0.1 -proot -e 'GRANT ALL PRIVILEGES ON test.* TO test@localhost IDENTIFIED BY "test" WITH GRANT OPTION'        
        mysql -uroot -h127.0.0.1 -proot -e 'GRANT ALL PRIVILEGES ON testcode.* TO test@localhost IDENTIFIED BY "testcode" WITH GRANT OPTION'
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
